
package:
    name: pyolog
    version: "4.3.0"

source:
    git_url: https://github.com/NSLS-II-CSX/pyOlog.git
    git_tag: refactor

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - setuptools
        - requests
        - keyring

test:
    imports:
        - pyOlog

about:
    home: http://olog.github.io/
    license: MIT
    summary: Python client for the OLog
