
package:
    name: pyolog
    version: "0.2.0"

source:
    git_url: https://github.com/NSLS-II-CSX/pyOlog.git

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - setuptools
        - requests
        - keyring
        - urllib3

test:
    imports:
        - pyOlog

about:
    home: http://olog.github.io/
    license: BSD
    summary: Python client for the OLog
